### PR TITLE
Pop-up dialog small changes

### PR DESCRIPTION
**Pull request by freenuxx**
3 commits
ps: my first ever Pull Request, hope I didn't mess anything :)

### CODE REVIEW

**Comment by lokal-profil** [comment]
Hi

Thanks for the Pull Request. The new look is definitely cleaner.

I see that this covers the "edit" symbol (which takes you to the lists) though. I can think of two ways to display it again:
*    it can be moved
*    left padding could be added (to all the content to make it look left aligned)

You are welcome to come with other suggestions though.

Another though:

*   Getting rid of the bullet points means it is harder to distinguish where fields end if they are long enough to be line-wrapped. Could this possibly be fixed through indenting continued lines?

**Comment by freenuxx** [comment]
As you suggested, I added some left padding to the ul to make room for the "edit" symbol (I still can't see it from my local server, but I managed to make the modifications). 

Bullet points: I added some padding-bottom to the 2nd child of the ul, in order to distinguish easily the Tite(bold) and the Artist, from the Location (3rd child of the ul).  I could add 2 or 3px more to make the separation more obvious (indenting continued lines I think it's not helping in this case).

I also sent an email with some suggestions and details on Task 3 and 4 (out of 4).

**Comment by lokal-profil** [comment]
Thanks. I'll take a look and see if I get the symbol to display. Will also reply to your e-mail later in the week. Great work!

**Comment by lokal-profil** [comment]
The reson you couldn't see the symbol was because the geo.json file included in the github repo was too old to support it. When I try your patch it now looks like [this](http://pasteboard.co/2NR12ggZ.png). 

If that works for you I'll just quickly check it on the mobile and then [rebase](https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request) your pull request and merge it.

**Comment by freenuxx** [comment]
On 04/24/2015 01:33 PM, lokal-profil wrote:
> The reson you couldn't see the symbol was because the geo.json file included in the github repo was too old to support it. When I try your patch it now looks like [this](http://pasteboard.co/2NR12ggZ.png). 
>
> If that works for you I'll just quickly check it on the mobile and then [rebase](https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request) your pull request and merge it.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/lokal-profil/ODOK/pull/22#issuecomment-95905177
I think it looks good.

I added another 2px padding-bottom to the Artist(2nd row), just to be
sure that is a clear separation between Title+Artist and Location.

I also read and did the "Rebase" thing. My last command was: "git push
-f", I hope that sent all the commits correctly.

Please let me know if I should do something else.

-- 
Please let me know if you received this email. Thank you!

**Comment by lokal-profil** [comment]
Squashed, rebased and merged! (with minor addition)

**Pull request closed without merging**
